version = 1
SPDX-PackageName = "ActionCollection"
SPDX-PackageSupplier = "Marco Martin <mart@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/libraries/actioncollection"

[[annotations]]
path = ["README.md", "autotests/data/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Marco Martin <mart@kde.org>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["src/actioncollection/KF6KirigamiActionCollectionConfig.cmake.in"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Marco Martin <mart@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["src/actioncollection/kirigamiactioncollection.qdocconf", "src/actioncollection/kirigamiactioncollection.qdoc", "src/actioncollection/kirigamiactioncollection-index.qdoc", "docs/includes/icongroup.qdocinc"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Marco Martin <mart@kde.org>"
SPDX-License-Identifier = "FSFAP"
